# User Configuration routing definition
user_config.settings_tab:
  route_name: user_config.settings
  title: 'Settings'
  base_route: user_config.settings

entity.user_config.canonical:
  route_name: entity.user_config.canonical
  base_route: entity.user_config.canonical
  title: 'View'

entity.user_config.edit_form:
  route_name: entity.user_config.edit_form
  base_route: entity.user_config.canonical
  title: 'Edit'

entity.user_config.delete_form:
  route_name:  entity.user_config.delete_form
  base_route:  entity.user_config.canonical
  title: Delete
  weight: 10
